"""empty message

Revision ID: 035a915147e6
Revises: 5e18c4231fba
Create Date: 2021-07-15 10:39:09.614475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035a915147e6'
down_revision = '5e18c4231fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image_styles', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image_styles', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('images', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image_styles', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image_styles', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
