"""re-fix comment cascade delete

Revision ID: 567f7ab58feb
Revises: 6f82a427a643
Create Date: 2021-07-19 10:28:05.462226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567f7ab58feb'
down_revision = '6f82a427a643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'coluna_teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('coluna_teste', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
