"""Criada nova coluna na DescriptionModel

Revision ID: 5e18c4231fba
Revises: bdb744a5a325
Create Date: 2021-07-14 15:51:59.506564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e18c4231fba'
down_revision = 'bdb744a5a325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptions', sa.Column('studio_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptions', 'studio_name')
    # ### end Alembic commands ###
