"""fix comment cascade delete

Revision ID: 6f82a427a643
Revises: 035a915147e6
Create Date: 2021-07-19 10:26:57.884439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f82a427a643'
down_revision = '035a915147e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('coluna_teste', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'coluna_teste')
    # ### end Alembic commands ###
