"""fixed cascade error in user

Revision ID: 87abe80199a0
Revises: 19eff8c62c83
Create Date: 2021-07-19 14:41:07.417651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87abe80199a0'
down_revision = '19eff8c62c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'colunatest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('colunatest', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
