"""added column description

Revision ID: bf3a43f7cd95
Revises: 83463de37b8e
Create Date: 2021-07-13 23:31:21.842611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3a43f7cd95'
down_revision = '83463de37b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptions', 'description')
    # ### end Alembic commands ###
