"""fixing cascade delete

Revision ID: f9a13071e68a
Revises: 87abe80199a0
Create Date: 2021-07-20 20:45:26.983320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a13071e68a'
down_revision = '87abe80199a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('tabelateste', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'tabelateste')
    # ### end Alembic commands ###
